build {
  sources = ["source.virtualbox-iso.rocky9"]

  # 1. Prepare the environment for Ansible
  provisioner "shell" {
    inline = [
      "sudo dnf install -y epel-release",
      "sudo dnf install -y ansible-core",
      "ansible-galaxy collection install community.general ansible.posix ansible.utils"
    ]
  }

  # 2. Automated Hardening
  # Points directly to the playbook generated by OpenSCAP
  provisioner "ansible-local" {
    playbook_file = "${path.root}/../ansible/main.yml"
    playbook_dir  = "${path.root}/../ansible"
    extra_arguments = [
      "--become",
      "--become-method=sudo", # Force Ansible to run as root to bypass CIS benchmarks temporarily
      "--extra-vars",
      "ansible_user=capstone"
    ]
  }

  # 3. Post-Hardening Override
  # This runs AFTER security rules are applied to unlock the user account (capstone)
  provisioner "shell" {
    inline = [
      # Disable expiration for the capstone user
      "sudo chage -I -1 -m 0 -M 99999 -E -1 capstone",

      # Force a password refresh to satisfy PAM authentication tokens
      "echo 'capstone:capstone' | sudo chpasswd",

      # Ensure SSH doesn't block the user (Optional: depends on scan results)
      "sudo sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config",
      "sudo firewall-cmd --permanent --add-service=ssh && sudo firewall-cmd --reload",
      "sudo systemctl restart sshd"
    ]
  }

  # 4. Final Cleanup
  # Runs cleanup script to sanitize the image
  provisioner "shell" {
    script = "${path.root}/../scripts/cleanup.sh"
  }

  # 5. Package the Secure Artifact
  # Outputs alongside existing rocky-base boxes
  post-processors {
    post-processor "vagrant" {
      output = "rocky9-hardened-v.1.box"
    }
  }
}