packer {
  required_plugins {
    virtualbox = {
      version = " >=1.1.0"
      source  = "github.com/hashicorp/virtualbox"
    }
    vagrant = {
      version = " >=1.1.0"
      source  = "github.com/hashicorp/vagrant"
    }
    ansible = {
      version = ">= 1.1.0"
      source  = "github.com/hashicorp/ansible"
    }
  }
}


variable "ssh-password" {
  type    = string
  default = "capstone"
  sensitive = true
  description = "temp password for packer to connect during builds"
}
# Official Rocky 9.7 Minimal ISO
source "virtualbox-iso" "rocky9" {
  vm_name          = "rocky-base"
  output_directory = "output-rocky9"

  iso_url      = "https://download.rockylinux.org/pub/rocky/9/isos/x86_64/Rocky-9.7-x86_64-minimal.iso"
  iso_checksum = "sha256:23a1ac1175d8ccada7195863914ef1237f584ff25f73bd53da410d5fffd882b0"

  http_directory = "${path.root}/http"
  guest_os_type  = "RedHat_64"
  headless       = false

  # Boot command for RHEL 9.x
  boot_wait = "10s"
  boot_command = [
    "<wait10>",
    "<tab><wait>",
    " inst.text inst.ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ks.cfg<enter>"
  ]

  # VirtualBox Guest Additions
  guest_additions_mode = "upload"
  guest_additions_path = "/tmp/VBoxGuestAdditions.iso"

  # SSH Settings for Vagrant
  ssh_username     = "capstone"
  ssh_password     = var.ssh-password
  ssh_timeout      = "30m"
  ssh_wait_timeout = "30m"

  shutdown_command = "echo '${var.ssh-password}' | sudo -S /sbin/halt -h -p"

  vboxmanage = [
    ["modifyvm", "{{ .Name }}", "--memory", "4096"],
    ["modifyvm", "{{ .Name }}", "--cpus", "4"],
    ["modifyvm", "{{ .Name }}", "--paravirtprovider", "kvm"],
    ["modifyvm", "{{ .Name }}", "--nictype1", "82540EM"],
    ["modifyvm", "{{ .Name }}", "--ioapic", "on"],
    ["modifyvm", "{{ .Name }}", "--nested-hw-virt", "off"],
    ["modifyvm", "{{ .Name }}", "--boot1", "disk"],
    ["modifyvm", "{{ .Name }}", "--boot2", "dvd"],
    ["modifyvm", "{{ .Name }}", "--boot3", "none"],
    ["modifyvm", "{{ .Name }}", "--boot4", "none"],
    ["modifyvm", "{{ .Name }}", "--vram", "128"],
    ["modifyvm", "{{ .Name }}", "--audio", "none"]
  ]
}

build {
  sources = ["source.virtualbox-iso.rocky9"]

  # 1. Prepare the environment for Ansible
  provisioner "shell" {
    inline = [
      "sudo dnf install -y epel-release",
      "sudo dnf install -y ansible-core",
      "ansible-galaxy collection install community.general ansible.posix ansible.utils"
    ]
  }

  # 2. Automated Hardening
  # Points directly to the playbook generated by OpenSCAP
  provisioner "ansible-local" {
    playbook_file = "${path.root}/../ansible/hardening.yml"
    # Force Ansible to run as root to bypass CIS benchmarks temporarily
    extra_arguments = [
        "--become",
        "--become-method=sudo"
    ]
  }

  # 3. Post-Hardening Override
  # This runs AFTER security rules are applied to unlock the user account (capstone)
  provisioner "shell" {
    inline = [
        # Disable expiration for the capstone user
        "sudo chage -I -1 -m 0 -M 99999 -E -1 capstone",
      
        # Force a password refresh to satisfy PAM authentication tokens
        "echo 'capstone:capstone' | sudo chpasswd",
      
        # Ensure SSH doesn't block the user (Optional: depends on scan results)
        "sudo sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config",
        "sudo firewall-cmd --permanent --add-service=ssh && sudo firewall-cmd --reload",
        "sudo systemctl restart sshd"
    ]
  }

  # 4. Final Cleanup
  # Runs cleanup script to sanitize the image
  provisioner "shell" {
    script = "${path.root}/../scripts/cleanup.sh"
  }
  
  # 5. Package the Secure Artifact
  # Outputs alongside existing rocky-base boxes
  post-processors {
    post-processor "vagrant" {
      output = "rocky9-hardened-v.1.box"
    }
  }
}