---
### This playbook is used to automate uploading public keys for SSH access to the servers.
- name: Managed SSH Access via GitHub Profiles
  hosts: all
  become: yes
  vars:
    # Define team's GitHub usernames here
    github_users:
      - spitlrr
      - bavila-490
      - JMVilla6
      - Katomic0
      - lillypadu

  tasks:
    - name: Ensure .ssh directory exists with correct permissions
      file:
        path: "/home/capstone/.ssh"
        state: directory
        mode: '0700'
        owner: "capstone"
        group: "capstone"

    - name: Deploy team public keys directly from GitHub
      ansible.posix.authorized_key:
        user: "capstone"
        state: present
        # Ansible automatically makes the HTTPS GET request to GitHub
        key: "https://github.com/{{ item }}.keys"
      loop: "{{ github_users }}"

    - name: Final CIS Permission Enforcement
      file:
        path: "/home/capstone/.ssh/authorized_keys"
        mode: '0600'
        owner: "capstone"
        group: "capstone"